config/routes.rb
Rails.application.routes.draw do
  root to: "homes#welcome"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: %i[show]
  resources :products, only: %i[index new create show]
  resources :addresses, only: %i[index new create edit update destroy]
  resources :carts, only: %i[index]
  resources :orders, only: %i[index new create]
  
  post 'cart_items/:id/add', to: "cart_items#add_quantity", as: "cart_item_add"
  post 'cart_items/:id/reduce', to: "cart_items#reduce_quantity", as: "cart_item_reduce"
  post 'cart_items/:product_id', to: "cart_items#create", as: "cart_items"
  get 'cart_items/:id', to: "cart_items#show", as: "cart_item"
  delete 'cart_items/:id', to: "cart_items#destroy"
end

app/views/shared/_product.html.erb
<div class = "mb-3" >
  <%= link_to 'View cart', carts_path %>
</div>
<% @products.each do |product| %>
  <div class = "mb-3">
    <% product.image.each do |image| %>
      <%= image_tag image, height: 200, width: 200, class: "mt-2 ml-4" %>
      <% break %>
    <% end %>
  </div>
  <div class = "mb-3">
    <%= "Product:- #{product.name}" %>
  </div>
  <div class = "mb-3">
    <%= "Price:- #{product.price}" %>
  </div>
  <%= link_to 'View Product', product_path(product) %><hr> 
<% end %>

app/views/shared/_side_bar.html.erb
<nav id = "sidebar">
  <% if user_signed_in? %>
    <div class = "col-md-6">
      <ul class = "nav nav-sidebar mt-2 ml-2">
        <% if current_user.present? %>
          <% if current_user.image.present? %>
            <%= image_tag current_user.image, height: 100, width:100, class: "rounded-circle mt-2 ml-4" %>
          <% else %>
            <i class = "fa fa-user fa-3x mt-2 ml-5"></i>
          <% end %>
          <li class = "sidebar mt-3 mb-4"><%= link_to "View_Profile", user_path %></li>
          <li class = "sidebar mb-4"><%= link_to "Update_Profile", edit_user_registration_path %></li>
          <li class = "sidebar mb-4"><%= link_to "Add_Product", new_product_path %></li>
          <li class = "sidebar mb-4"><%= link_to "View_Product", products_path %></li>
          <li class = "sidebar mb-4"><%= link_to "Add_Address", new_address_path %></li>
          <li class = "sidebar mb-4"><%= link_to "View_Address", addresses_path %></li>
          <li class = "sidebar mb-4"><%= link_to "View_Order", orders_path %></li>
          <li class = "mb-4"><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li> 
        <% end %>
      </ul>
    </div>
  <% end %>
</nav>