config/routes.rb
Rails.application.routes.draw do
  root to: "homes#welcome"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: %i[show]
  resources :products, only: %i[index new create show]
  resources :addresses, only: %i[index new create edit update destroy]
  resources :carts, only: %i[index]
  resources :orders, only: %i[index new create]
  
  post 'cart_items/:id/add', to: "cart_items#add_quantity", as: "cart_item_add"
  post 'cart_items/:id/reduce', to: "cart_items#reduce_quantity", as: "cart_item_reduce"
  post 'cart_items/:product_id', to: "cart_items#create", as: "cart_items"
  get 'cart_items/:id', to: "cart_items#show", as: "cart_item"
  delete 'cart_items/:id', to: "cart_items#destroy"
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
  belongs_to :user
  
  def sub_total
    cart_items.sum(&:total_price)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :find_cart, only: %i[index]
  
  def index; end
  
  private
  def find_cart
    @cart = current_user.cart
  end
end

app/views/carts/index.html.erb
<h2>Cart Details</h2>
<% @cart.cart_items.each do |cart_item| %>
  <ul>
    <li>Item: <%= cart_item.product.name %>/ Price: <%= cart_item.product.price %>/ Quantity: <%= cart_item.quantity %>/ Total Price: <%= cart_item.total_price %>
    </li>
    <ul>
      <li>
        <%= link_to "Add one", cart_item_add_path(id: cart_item), method: :post %>
        <%= link_to "Reduce one", cart_item_reduce_path(id: cart_item), method: :post %>
      </li>
      <li>
        <%= link_to "Remove item", cart_item_path(cart_item), method: :delete %>
      </li>
    </ul>
  </ul>  
<% end %>
<h3>Sub total: <%= @cart.sub_total %> Rs.</h3>
<%= link_to "Proceed to checkout", new_order_path %><br>
<%= link_to "Back", products_path %>

app/views/carts/show.html.erb
<h2>Cart show</h2>
<ul>
  <% @cart.cart_items.each do |cart_item| %>
    <li>Item: <%= cart_item.product.name %>/ Price: <%= cart_item.product.price %>/ Quantity: <%= cart_item.quantity %>/ Total Price: <%= cart_item.total_price %>
    <ul>
      <li>
        <%= link_to "Add one", cart_item_add_path(id: cart_item), method: :post %>
        <%= link_to "Reduce one", cart_item_reduce_path(id: cart_item), method: :post %>
      </li>
      <li>
        <%= link_to "Remove item", cart_item_path(cart_item), method: :delete %>
      </li>
    </ul>
  <% end %>
</ul>
<h3>Sub total: <%= @cart.sub_total %> Rs.</h3>
<%= link_to "Empty cart", cart_path(@current_cart), method: :delete, data: {confirm: "Are you sure?"} %>