config/routes.rb
Rails.application.routes.draw do
  root to: "homes#welcome"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: %i[show]
  resources :products, only: %i[index new create show]
  resources :addresses, only: %i[index new create edit update destroy]
  resources :carts, only: %i[index]
  resources :orders, only: %i[index new create]
  
  post 'cart_items/:id/add', to: "cart_items#add_quantity", as: "cart_item_add"
  post 'cart_items/:id/reduce', to: "cart_items#reduce_quantity", as: "cart_item_reduce"
  post 'cart_items/:product_id', to: "cart_items#create", as: "cart_items"
  get 'cart_items/:id', to: "cart_items#show", as: "cart_item"
  delete 'cart_items/:id', to: "cart_items#destroy"
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :load_address, only: %i[edit update destroy]

  def index
    @address = current_user.addresses.all
  end

  def new
    @address = current_user.addresses.new
  end
  
  def create
    @address = current_user.addresses.new(address_params)
    @user = current_user
    if @address.save
      flash[:notice] = "Address Added!"
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
 
  def edit; end
  
  def update
    if @address != nil && @address.update(address_update_params)
      flash[:notice] = "address updated!"
      redirect_to addresses_path
    else
      flash[:notice] = "Address update unsuccessfull!"
      render :edit
    end
  end
  
  def destroy 
    @address.destroy
    flash[:success] = "address destroyed."
    redirect_to addresses_path
  end
  
  private
  def address_params
    params.require(:address).permit(:user_id, :house_no, :street, :city, :state, :country, :pincode)
  end

  def address_update_params
    params.require(:address).permit(:house_no, :street, :city, :state, :country, :pincode)
  end
  
  def load_address
    @address = current_user.addresses.find_by_id(address_id_params[:id])
  end
  
  def address_id_params
    params.permit(:id)
  end
end

app/views/addresses/edit.html.erb
<div class = "row">
  <div class = "column">
    <%= render "shared/side_bar" %>
  </div>
  <div class = "column">
    <div class = containers>
      <h1>Update address</h1>
      <%= form_for @address, html: { class: 'form-horizontal center' } do |f| %>
        <div class = 'form-group row'>
          <%= f.label :house_no, class: 'col-md-3' %>
          <div class = 'col-md-9'>
            <%= f.text_field :house_no, class: 'form-control' %>
          </div>
        </div>
      <div class = 'form-group row'>
        <%= f.label :street, class: 'col-md-3' %>
        <div class = 'col-md-9'>
          <%= f.text_field :street, class: 'form-control' %>
        </div>
      </div>
      <div class = 'form-group row'>
        <%= f.label :city, class: 'col-md-3' %>
        <div class = 'col-md-9'>
          <%= f.text_field :city, class: 'form-control' %>
        </div>
      </div>
      <div class = 'form-group row'>
        <%= f.label :state, class: 'col-md-3' %>
        <div class = 'col-md-9'>
          <%= f.text_field :state, class: 'form-control' %>
        </div>
      </div>
      <div class = 'form-group row'>
        <%= f.label :country, class: 'col-md-3' %>
        <div class = 'col-md-9'>
          <%= f.text_field :country, class: 'form-control' %>
        </div>
      </div>
      <div class = 'form-group row'>
        <%= f.label :pincode, class: 'col-md-3' %>
        <div class = 'col-md-9'>
          <%= f.text_field :pincode, class: 'form-control' %>
        </div>
      </div>
      <%= f.submit "Update", class: 'btn btn-primary btn-sm' %>
    <% end %>
  </div>
</div>

app/views/addresses/index.html.erb
<% @address.each do |address| %>
  <div class = "mb-3">
    <%= "Address:- #{address.house_no}, #{address.street}, #{address.city}" %>
  </div>
  <div class = "mb-3">
    <%= "#{address.state}, #{address.country}" %>
  </div>
  <div class = "mb-3">
    <%= "pin-code #{address.pincode} " %>
  </div>
  <%= link_to "edit", edit_address_path(address) %>
  <%= link_to "delete", address_path(address), method: :delete %>
  <hr>
<% end %>

app/views/addresses/new.html.erb
<div class = containers>
  <h1>Add Address</h1>
  <%= form_for @address, html: { class: 'form-horizontal center' } do |f| %>
    <div class = 'form-group row'>
      <%= f.label :Userid, class: 'col-md-3' %>
      <div class = 'col-md-9'>
        <%= f.text_field :user_id, value: current_user.id, class: 'form-control' %>
      </div>
    </div>
    <div class = 'form-group row'>
      <%= f.label :House_no, class: 'col-md-3' %>
      <div class = 'col-md-9'>
        <%= f.text_field :house_no, class: 'form-control' %>
      </div>
    </div>
    <div class = 'form-group row'>
      <%= f.label :street, class: 'col-md-3' %>
      <div class = 'col-md-9'>
        <%= f.text_area :street, step: :any, class: 'form-control' %>
      </div>
    </div>
    <div class = 'form-group row'>
      <%= f.label :city, class: 'col-md-3' %>
      <div class = 'col-md-9'>
        <%= f.text_field :city, class: 'form-control' %>
      </div>
    </div>
    <div class = 'form-group row'>
      <%= f.label :state, class: 'col-md-3' %>
      <div class = 'col-md-9'>
        <%= f.text_field :state, class: 'form-control' %>
      </div>
    </div>
    <div class = 'form-group row'>
      <%= f.label :country, class: 'col-md-3' %>
      <div class = 'col-md-9'>
        <%= f.text_field :country, class: 'form-control' %>
      </div>
    </div>
    <div class = 'form-group row'>
      <%= f.label :pincode, class: 'col-md-3' %>
      <div class = 'col-md-9'>
        <%= f.number_field :pincode, class: 'form-control' %>
      </div>
    </div>
    <%= f.submit "Add", class: 'btn btn-primary btn-sm' %>
  <% end %>
</div>

app/views/addresses/show.html.erb
<% @address.each do |address| %>
  <div class = "mb-3">
    <%= "Address:- #{address.house_no}, #{address.street}, #{address.city}" %>
  </div>
  <div class = "mb-3">
    <%= "#{address.state}, #{address.country}" %>
  </div>
  <div class = "mb-3">
    <%= "pin-code #{address.pincode} " %>
  </div><hr>
<% end %>