config/routes.rb
Rails.application.routes.draw do
  root to: "homes#welcome"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: %i[show]
  resources :products, only: %i[index new create show]
  resources :addresses, only: %i[index new create edit update destroy]
  resources :carts, only: %i[index]
  resources :orders, only: %i[index new create]
  
  post 'cart_items/:id/add', to: "cart_items#add_quantity", as: "cart_item_add"
  post 'cart_items/:id/reduce', to: "cart_items#reduce_quantity", as: "cart_item_reduce"
  post 'cart_items/:product_id', to: "cart_items#create", as: "cart_items"
  get 'cart_items/:id', to: "cart_items#show", as: "cart_item"
  delete 'cart_items/:id', to: "cart_items#destroy"
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :image, dependent: :destroy
  belongs_to :user, optional: true
  has_many :cart_items
  
  validates :name, :quantity, :description, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }, presence: true
  
  def self.search(search)
    if search
      where('lower(name) LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.search(params[:search])
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(product_params)
    @user = current_user
    if @product.save
      flash[:notice] = "Product Created!"
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  
  def show
   @product = Product.find_by_id(view_product_params[:id])
  end
  
  private
  def product_params
    params.require(:product).permit(:name, :user_id, :price, :description, :quantity, image: [])
  end
  
  def view_product_params
    params.permit(:id)
  end
end

app/views/products/index.html.erb
<div class = "col-sm-1">
  <%= link_to 'Back', user_path(current_user) %>
</div>
<%= "Welcome #{current_user.full_name}" %>

<%= form_tag products_path, :method => 'get', :id => "products_search", remote: true do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <div id="products">
    <%= render "shared/product", collection: @products %>
  </div>
<% end %>

app/views/products/index.js.erb
$("#products").html("<%= escape_javascript(render "shared/product") %>");

app/views/products/new.html.erb
<div class = containers>
  <h1>Add Product</h1>
  <%= form_for @product, html: { class: 'form-horizontal center' } do |f| %>
    <div class = 'form-group row'>
      <%= f.label :product, class: 'col-md-3' %>
      <div class = 'col-md-9'>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class = 'form-group row'>
      <%= f.label :Userid, class: 'col-md-3' %>
      <div class = 'col-md-9'>
        <%= f.text_field :user_id, value: current_user.id, class: 'form-control' %>
      </div>
    </div>
    <div class = 'form-group row'>
      <%= f.label :price, class: 'col-md-3' %>
      <div class = 'col-md-9'>
        <%= f.number_field :price, step: :any, class: 'form-control' %>
      </div>
    </div>
    <div class = 'form-group row'>
      <%= f.label :desription, class: 'col-md-3' %>
      <div class = 'col-md-9'>
        <%= f.text_area :description, class: 'form-control' %>
      </div>
    </div>
    <div class = 'form-group row'>
      <%= f.label :quantity, class: 'col-md-3' %>
      <div class = 'col-md-9'>
        <%= f.number_field :quantity, class: 'form-control' %>
      </div>
    </div>
    <div class = 'form-group row'>
      <%= f.label :images, class: 'col-md-3' %>
      <div class = 'col-md-9'>
        <%= f.file_field :image, multiple: true,  class: 'form-control' %>
      </div>
    </div>
    <%= f.submit "Add", class: 'btn btn-primary btn-sm' %>
  <% end %>
</div>

app/views/products/show.html.erb
<%= "Welcome #{current_user.full_name}" %>
<div class = "mb-3">
  <%= "Product:- " %>
  <%= @product.name %>
</div>
<div class = "mb-3">
  <%= "Price:-" %>
  <%= @product.price %>
</div>
<div class = "mb-3">
  <%= "Description:- " %>
  <%= @product.description %>
</div>
<% if @product.image.present? %>
  <% @product.image.each do |image| %>
    <%= image_tag image, height: 200, width: 200, class: "mt-2 ml-4" %>
  <% end %>
<% end %>
<%= button_to "Add #{@product.name} to cart", cart_items_path(@product) %>